name: Update Markdown

on:
  # Split into two separate triggers
  # 1. PR with path filters
  pull_request:
    branches:
      - main
    paths:
      - "cmd/**"
      - "sdk/**"
  
  # 2. Comments without path filters
  issue_comment:
    types: [created]

# Add permissions block to allow reading PR comments
permissions:
  contents: write
  pull-requests: write
  issues: read
  statuses: write

jobs:
  update-md:
    # Only run on PRs or on /update-md comments on PRs
    if: |
      (github.event_name == 'pull_request') ||
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '/update-md') && github.event.issue.pull_request)
    runs-on: ubuntu-latest

    steps:
      # Add this step to debug the event context
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"

      - uses: xt0rted/pull-request-comment-branch@v2
        id: comment-branch
        if: github.event_name == 'issue_comment'

      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event_name == 'issue_comment' && steps.comment-branch.outputs.head_ref || github.head_ref }}
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Build avalanche-cli
        run: |
          chmod +x ./scripts/build.sh
          ./scripts/build.sh

      - name: Add avalanche to PATH
        run: echo "${{ github.workspace }}/bin" >> $GITHUB_PATH

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          # If you need additional dependencies, install them here
          # pip install -r requirements.txt

      - name: Generate CLI MD
        id: generate_cli_md
        run: |
          python .github/scripts/cli_scraper.py

      - name: Generate SDK MD
        id: generate_sdk_md
        run: |
          python .github/scripts/sdk_doc.py

      - name: Commit files
        uses: ChromeQ/commit@v2.0.0
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            cmd/commands.md
            sdk/SDK.md
          commit-message: "chore: Update MD files [skip ci]"
          # Commit back to the head branch so changes stay in the PR
          ref: ${{ github.head_ref }}
